– MySQL Script generated by MySQL Workbench – Mon Nov 27 13:34:15 2023 –
Model: New Model Version: 1.0 – MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0; SET
@OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0; SET
@OLD_SQL_MODE=@@SQL_MODE,
SQL_MODE=‘ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION’;

CREATE SCHEMA IF NOT EXISTS sistemaestoque DEFAULT CHARACTER SET utf8mb3
; USE sistemaestoque ;

CREATE TABLE IF NOT EXISTS sistemaestoque.categoria ( id INT NOT NULL
AUTO_INCREMENT, descricao VARCHAR(45) NULL DEFAULT NULL, PRIMARY KEY
(id)) ENGINE = InnoDB AUTO_INCREMENT = 7 DEFAULT CHARACTER SET =
utf8mb3;

CREATE TABLE IF NOT EXISTS sistemaestoque.unidademedida ( idunidade INT
NOT NULL AUTO_INCREMENT, descricao VARCHAR(20) NOT NULL, PRIMARY KEY
(idunidade)) ENGINE = InnoDB AUTO_INCREMENT = 4 DEFAULT CHARACTER SET =
utf8mb3;

CREATE TABLE IF NOT EXISTS sistemaestoque.produto ( id INT NOT NULL
AUTO_INCREMENT, descricao VARCHAR(200) NULL DEFAULT NULL, estoqueMinimo
VARCHAR(45) NULL DEFAULT NULL, observacao VARCHAR(200) NULL DEFAULT
NULL, codigoProduto INT NULL DEFAULT NULL, idCategoria INT NOT NULL,
idUnidadeMedida INT NOT NULL, dataCadastro TIMESTAMP NULL DEFAULT
CURRENT_TIMESTAMP, PRIMARY KEY (id, idCategoria, idUnidadeMedida), INDEX
fk_produto_categoria_idx (idCategoria ASC) VISIBLE, INDEX
fk_produto_unidade1_idx (idUnidadeMedida ASC) VISIBLE, CONSTRAINT
fk_produto_categoria FOREIGN KEY (idCategoria) REFERENCES
sistemaestoque.categoria (id), CONSTRAINT fk_produto_unidade1 FOREIGN
KEY (idUnidadeMedida) REFERENCES sistemaestoque.unidademedida
(idunidade)) ENGINE = InnoDB AUTO_INCREMENT = 28 DEFAULT CHARACTER SET =
utf8mb3;

CREATE TABLE IF NOT EXISTS sistemaestoque.estoque ( id INT NOT NULL
AUTO_INCREMENT, quantidade DOUBLE NULL DEFAULT NULL, dataMovimentacao
VARCHAR(45) NULL DEFAULT NULL, idProduto INT NOT NULL, PRIMARY KEY (id,
idProduto), INDEX fk_estoque_produto1_idx (idProduto ASC) VISIBLE,
CONSTRAINT fk_estoque_produto1 FOREIGN KEY (idProduto) REFERENCES
sistemaestoque.produto (id)) ENGINE = InnoDB AUTO_INCREMENT = 9 DEFAULT
CHARACTER SET = utf8mb3;

CREATE TABLE IF NOT EXISTS sistemaestoque.fornecedor ( id INT NOT NULL
AUTO_INCREMENT, nome VARCHAR(100) NOT NULL, cpf_cnpj VARCHAR(45) NULL
DEFAULT NULL, endereco VARCHAR(45) NULL DEFAULT NULL, cidade VARCHAR(45)
NULL DEFAULT NULL, telefone VARCHAR(45) NULL DEFAULT NULL, email
VARCHAR(45) NULL DEFAULT NULL, contato VARCHAR(45) NULL DEFAULT NULL,
bairro VARCHAR(100) NULL DEFAULT NULL, dataCadastro TIMESTAMP NULL
DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (id)) ENGINE = InnoDB
AUTO_INCREMENT = 6 DEFAULT CHARACTER SET = utf8mb3;

CREATE TABLE IF NOT EXISTS sistemaestoque.funcionario ( id INT NOT NULL
AUTO_INCREMENT, nome VARCHAR(45) NULL DEFAULT NULL, contato VARCHAR(45)
NULL DEFAULT NULL, cidade VARCHAR(45) NULL DEFAULT NULL, cpf_cnpj
VARCHAR(20) NULL DEFAULT NULL, cargo VARCHAR(50) NULL DEFAULT NULL,
dataCadastro TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (id))
ENGINE = InnoDB AUTO_INCREMENT = 7 DEFAULT CHARACTER SET = utf8mb3;

CREATE TABLE IF NOT EXISTS sistemaestoque.movimenta_estoque_compra ( id
INT NOT NULL AUTO_INCREMENT, quantidade DOUBLE NULL DEFAULT NULL,
IdProduto INT NOT NULL, idFornecedor INT NOT NULL, dataMovimentacao
TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (id, IdProduto,
idFornecedor), INDEX fk_movimenta_estoque_entrada_produto1_idx
(IdProduto ASC) VISIBLE, INDEX
fk_movimenta_estoque_compra_fornecedor1_idx (idFornecedor ASC) VISIBLE,
CONSTRAINT fk_movimenta_estoque_compra_fornecedor1 FOREIGN KEY
(idFornecedor) REFERENCES sistemaestoque.fornecedor (id), CONSTRAINT
fk_movimenta_estoque_entrada_produto1 FOREIGN KEY (IdProduto) REFERENCES
sistemaestoque.produto (id)) ENGINE = InnoDB AUTO_INCREMENT = 24 DEFAULT
CHARACTER SET = utf8mb3;

CREATE TABLE IF NOT EXISTS sistemaestoque.movimenta_estoque_venda ( id
INT NOT NULL AUTO_INCREMENT, quantidade DOUBLE NULL DEFAULT NULL,
idFuncionario INT NOT NULL, idProduto INT NOT NULL, dataMovimentacao
TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP, observacao VARCHAR(200) NULL
DEFAULT NULL, PRIMARY KEY (id, idFuncionario, idProduto), INDEX
fk_movimenta_estoque_saida_funcionario1_idx (idFuncionario ASC) VISIBLE,
INDEX fk_movimenta_estoque_saida_produto1_idx (idProduto ASC) VISIBLE,
CONSTRAINT fk_movimenta_estoque_saida_funcionario1 FOREIGN KEY
(idFuncionario) REFERENCES sistemaestoque.funcionario (id), CONSTRAINT
fk_movimenta_estoque_saida_produto1 FOREIGN KEY (idProduto) REFERENCES
sistemaestoque.produto (id)) ENGINE = InnoDB AUTO_INCREMENT = 27 DEFAULT
CHARACTER SET = utf8mb3;

CREATE TABLE IF NOT EXISTS sistemaestoque.usuario ( id INT NOT NULL
AUTO_INCREMENT, login VARCHAR(45) NULL DEFAULT NULL, senha VARCHAR(45)
NULL DEFAULT NULL, usuariocol VARCHAR(45) NULL DEFAULT NULL, PRIMARY KEY
(id)) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb3;

DELIMITER
$$
CREATE TRIGGER `after_insert_produto`
AFTER INSERT ON `produto`
FOR EACH ROW
BEGIN
    DECLARE valorPadrao DOUBLE DEFAULT 0.0;
    INSERT INTO estoque (quantidade, dataMovimentacao, idProduto)
    VALUES (valorPadrao, NEW.dataCadastro, NEW.id);
END$$

CREATE TRIGGER tr_atualizar_dataMovimentacao BEFORE UPDATE ON estoque
FOR EACH ROW BEGIN IF NEW.quantidade <> OLD.quantidade THEN SET
NEW.dataMovimentacao = NOW(); END IF; END$$ DELIMITER ;
